backend:
  name: git-gateway
  branch: main # Branch to update (master by default)

media_folder: "src/.vuepress/public/upload"
public_folder: "/upload"

# This line should *not* be indented
publish_mode: editorial_workflow

locale: 'zh'

collections:
  - name: "文章" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "src" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
