name: 部署文档

on:
  push:
    branches:
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs
          folder: src
